apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: "cache"
      emptyDir: {}
  containers:
    - image: gcr.io/kuar-demo/kuard-arm64:1
      name: kuard
      volumeMounts:
        - mountPath: "/data"
          name: "cache"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
    - image: redis
      name: redis
      volumeMounts:
        - mountPath: "/data"
          name: "cache"
      ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
